package main

import (
	"fmt"
	"strings"
)

func gcdOfStrings(str1, str2 string) string {
	res, ans := make([]string, 0), ""
	l1, l2 := len(str1), len(str2)
	for i := 1; i <= l1; i++ {
		tmp := str1[:i]
		if l1%len(tmp) == 0 {
			if strings.Repeat(tmp, l1/len(tmp)) == str1 {
				res = append(res, tmp)
			}
		}
	}
	for _, v := range res {
		if l2%len(v) == 0 {
			if strings.Repeat(v, l2/len(v)) == str2 && len(v) > len(ans) {
				ans = v
			}
		}
	}
	return ans
}

func main() {
	fmt.Println(gcdOfStrings("ABCABCABCABC", "ABC"))
	//fmt.Println(gcdOfStrings("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
	//"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
	//"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
	//"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
	//"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	//"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
	//	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
	//	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
	//	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"+
	//	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"))
}
